name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - bson
  - lz4
  - lzo
  - pytest
  - pandas
  - dask
  - pytest-cov
  - thrift
  - numpy
  - cramjam
  - pyspark=3.3
  - packaging
  - orjson
  - ujson
  - python-rapidjson
  - pyarrow
